
//# _DEF(OP)
#ifdef _DEF

_DEF(AST_NONE),
_DEF(AST_TRANSLATION_UNIT),
_DEF(AST_IMPORT),
_DEF(AST_GET_VARIABLE),
_DEF(AST_FIELD_INITIALIZER),
_DEF(AST_VARIABLE_DECLARATION),
_DEF(AST_STRUCT_DECLARATION),
_DEF(AST_FUNCTION_DECLARATION),
_DEF(AST_FUNCTION_CALL),
_DEF(AST_WHILE_LOOP),
_DEF(AST_FOR_LOOP),
_DEF(AST_ARRAY_INITIALIZER_LIST),
_DEF(AST_STRUCT_INITIALIZER_LIST),

_DEF(AST_CAST_STATEMENT),
_DEF(AST_IF_STATEMENT),
_DEF(AST_RETURN),
_DEF(AST_BREAK),
_DEF(AST_CONTINUE),
_DEF(AST_BOOL_LITERAL),
_DEF(AST_CHAR_LITERAL),
_DEF(AST_INTEGER_LITERAL),
_DEF(AST_STRING_LITERAL),
_DEF(AST_BINARY_OP),
_DEF(AST_UNARY_OP),
_DEF(AST_COUNT),

#endif
